### ISSUE TITLE
[Question] Nuget package support?

### ISSUE THREAD

**Issue by waylaa** [Fusion86/ScrcpyNet#2]
Will there be a nuget package for this client?
It would be nice if that could happen so everyone can integrate this client to their projects.

**Comment by Fusion86** [comment]
Hmm I guess I could create a package. To be honest I just created this for fun, without the intention of it actually working on other's computers. I'll also have to look into how the dependencies are packaged (and their licenses).

**Comment by Fusion86** [comment]
I finally managed to create a working nuget package [ScrcpyNet ](https://www.nuget.org/packages/ScrcpyNet/)and [ScrcpyNet.Wpf](https://www.nuget.org/packages/ScrcpyNet.Wpf/). ScrcpyNet.Avalonia is still work in progress.
