### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by ZSXinXing** [Fusion86/ScrcpyNet#9]
When using it, the CPU usage is too high. Can you solve it or provide a private chat solution? I guess it is caused by the rendering of the screen.

**Comment by Fusion86** [comment]
Yeah, using Task Manager CPU metrics it looks like it is about 5x slower than the original scrcpy implementation, at least on my pc. The rendering isn't the actual issue, the [VideoStreamDecoder.cs](https://github.com/Fusion86/ScrcpyNet/blob/master/src/ScrcpyNet/VideoStreamDecoder.cs) is just kinda slow. Unfortunately I don't think I'll fix this anytime soon (if ever), seeing as I don't really use this anymore.

**Comment by ZSXinXing** [comment]
> Yeah, using Task Manager CPU metrics it looks like it is about 5x slower than the original scrcpy implementation, at least on my pc. The rendering isn't the actual issue, the [VideoStreamDecoder.cs](https://github.com/Fusion86/ScrcpyNet/blob/master/src/ScrcpyNet/VideoStreamDecoder.cs) is just kinda slow. Unfortunately I don't think I'll fix this anytime soon (if ever), seeing as I don't really use this anymore.

My God, my project has become scrcpynet, but it cannot be used normally due to high cpu usage, can you solve it?  Or improve the solution to me

**Comment by ZSXinXing** [comment]
> 是的，使用任务管理器 CPU 指标，它看起来比原来的 scrcpy 实现慢了大约 5 倍，至少在我的电脑上是这样。渲染不是实际问题，[VideoStreamDecoder.cs](https://github.com/Fusion86/ScrcpyNet/blob/master/src/ScrcpyNet/VideoStreamDecoder.cs)有点慢。不幸的是，我认为我不会很快解决这个问题（如果有的话），因为我不再使用它了。

I found that the problem of high CPU usage is the use of WriteableBitmap. When the frame is converted to WriteableBitmap, the CPU usage will be very high

**Comment by Fusion86** [comment]
The latest commit (73c66a85caa546bafe54ed261267a345224a86c9) should have fixed this issue. Could you test it again? The nuget packages haven't been updated yet.

**Comment by ZSXinXing** [comment]
Yes, the problem has been fixed, thank you for your dedication
